version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - CASECON_LICENSE_KEY=supercalifragilisticexpialidocious
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
