services:
  - type: web
    name: caseconweb-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000

  - type: web
    name: caseconweb-frontend
    env: node
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "cd frontend && npm run preview -- --port 3000"
    staticPublishPath: frontend/dist
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://github.com/jonobrands/JDP.git
