services:
  - type: web
    name: caseconweb-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"

  - type: web
    name: caseconweb-frontend
    env: node
    rootDir: frontend
    buildCommand: npm ci && npm install --no-save serve && npm run build
    startCommand: npx serve -s dist -l $PORT
    plan: free
    autoDeploy: true
    envVars:
      # Provide the backend host to the React app at build time
      - key: REACT_APP_API_BASE
        fromService:
          type: web
          name: caseconweb-backend
          property: host
      # UID API base will be derived as `${REACT_APP_API_BASE}/uids` by the frontend resolver
